### ISSUE TITLE
Postgres initialization scripts renders incorrectly on Docker Hub

### ISSUE THREAD

**Issue by Wieschie** [docker-library/docs#1560] opened 2019-08-20 21:18 UTC
Starting on [line 109](https://github.com/docker-library/docs/blame/master/postgres/content.md#L109) through the Additional Extensions section, the Postgres content does not render correctly on [Docker Hub](https://hub.docker.com/_/postgres).  I've been unable to reproduce this - it renders fine on my machine and on GitHub's preview.

**Comment by tianon** [comment] 2019-08-20 21:21
Duplicate of https://github.com/docker-library/docs/issues/1558; see also https://github.com/docker/hub-feedback/issues/1849

**Closed by tianon** 2019-08-20 21:21 UTC
