### ISSUE TITLE
docker-php-ext-configure gd... causes error after update to Buster

### ISSUE THREAD

**Issue by andriy-f** [docker-library/docs#1531] opened 2019-07-14 17:58 UTC
Command `docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/` causes error for php:7.1-fpm after update to Buster (took from readme):

configure: error: freetype-config not found.

**Comment by alexkunin** [comment] 2019-07-15 06:37
I see the same here, was using `php:7.3-apache` (which now resolves to `php:7.3.7-apache-buster`), and it was working fine until I tried to rebuild image today. 

Downgrading to specifically `php:7.3.6-apache`, all works fine now.

As for exact point of failure, it's the same as in the comment above, and I believe it looks like the example on Docker Hub page. Here is first half of my Dockerfile:

```
FROM php:7.3.6-apache AS app

ARG APP_ENV=prod
ARG APP_DIR=/app

RUN apt-get update && apt-get install --no-install-recommends -y \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libpng-dev \
        libzip-dev \
    && docker-php-ext-configure \
        gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install \
        pdo_mysql \
        gd \
        opcache \
        zip \
    && apt-get remove -y \
        gcc \
        g++ \
    && apt-get autoremove -y \
    && rm -rf /var/lib/apt/lists/*
```

And here is output with error:

```
Step 34/52 : RUN apt-get update && apt-get install --no-install-recommends -y         libfreetype6-dev         libjpeg62-turbo-dev         libpng-dev         libzip-dev     && docker-php-ext-configure         gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/     && docker-php-ext-install         pdo_mysql         gd         opcache         zip     && apt-get remove -y         gcc         g++     && apt-get autoremove -y     && rm -rf /var/lib/apt/lists/*
 ---> Running in 7497950a2981
Get:1 http://cdn-fastly.deb.debian.org/debian buster InRelease [118 kB]
Get:2 http://cdn-fastly.deb.debian.org/debian buster-updates InRelease [46.8 kB]
Get:3 http://security-cdn.debian.org/debian-security buster/updates InRelease [39.1 kB]
Get:4 http://cdn-fastly.deb.debian.org/debian buster/main amd64 Packages [7897 kB]
Get:5 http://security-cdn.debian.org/debian-security buster/updates/main amd64 Packages [22.8 kB]
Fetched 8124 kB in 2s (3774 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
The following package was automatically installed and is no longer required:
  sensible-utils
Use 'apt autoremove' to remove it.
The following additional packages will be installed:
  libfreetype6 libjpeg62-turbo libpng16-16 libzip4 zlib1g-dev
Recommended packages:
  freetype2-doc libpng-tools
The following NEW packages will be installed:
  libfreetype6 libfreetype6-dev libjpeg62-turbo libjpeg62-turbo-dev libpng-dev
  libpng16-16 libzip-dev libzip4 zlib1g-dev
0 upgraded, 9 newly installed, 0 to remove and 0 not upgraded.
Need to get 2279 kB of archives.
After this operation, 6613 kB of additional disk space will be used.
Get:1 http://cdn-fastly.deb.debian.org/debian buster/main amd64 libpng16-16 amd64 1.6.36-6 [292 kB]
Get:2 http://cdn-fastly.deb.debian.org/debian buster/main amd64 libfreetype6 amd64 2.9.1-3 [379 kB]
Get:3 http://cdn-fastly.deb.debian.org/debian buster/main amd64 zlib1g-dev amd64 1:1.2.11.dfsg-1 [214 kB]
Get:4 http://cdn-fastly.deb.debian.org/debian buster/main amd64 libpng-dev amd64 1.6.36-6 [300 kB]
Get:5 http://cdn-fastly.deb.debian.org/debian buster/main amd64 libfreetype6-dev amd64 2.9.1-3 [543 kB]
Get:6 http://cdn-fastly.deb.debian.org/debian buster/main amd64 libjpeg62-turbo amd64 1:1.5.2-2+b1 [134 kB]
Get:7 http://cdn-fastly.deb.debian.org/debian buster/main amd64 libjpeg62-turbo-dev amd64 1:1.5.2-2+b1 [208 kB]
Get:8 http://cdn-fastly.deb.debian.org/debian buster/main amd64 libzip4 amd64 1.5.1-4 [50.7 kB]
Get:9 http://cdn-fastly.deb.debian.org/debian buster/main amd64 libzip-dev amd64 1.5.1-4 [158 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 2279 kB in 0s (6092 kB/s)
Selecting previously unselected package libpng16-16:amd64.
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 13530 files and directories currently installed.)
Preparing to unpack .../0-libpng16-16_1.6.36-6_amd64.deb ...
Unpacking libpng16-16:amd64 (1.6.36-6) ...
Selecting previously unselected package libfreetype6:amd64.
Preparing to unpack .../1-libfreetype6_2.9.1-3_amd64.deb ...
Unpacking libfreetype6:amd64 (2.9.1-3) ...
Selecting previously unselected package zlib1g-dev:amd64.
Preparing to unpack .../2-zlib1g-dev_1%3a1.2.11.dfsg-1_amd64.deb ...
Unpacking zlib1g-dev:amd64 (1:1.2.11.dfsg-1) ...
Selecting previously unselected package libpng-dev:amd64.
Preparing to unpack .../3-libpng-dev_1.6.36-6_amd64.deb ...
Unpacking libpng-dev:amd64 (1.6.36-6) ...
Selecting previously unselected package libfreetype6-dev:amd64.
Preparing to unpack .../4-libfreetype6-dev_2.9.1-3_amd64.deb ...
Unpacking libfreetype6-dev:amd64 (2.9.1-3) ...
Selecting previously unselected package libjpeg62-turbo:amd64.
Preparing to unpack .../5-libjpeg62-turbo_1%3a1.5.2-2+b1_amd64.deb ...
Unpacking libjpeg62-turbo:amd64 (1:1.5.2-2+b1) ...
Selecting previously unselected package libjpeg62-turbo-dev:amd64.
Preparing to unpack .../6-libjpeg62-turbo-dev_1%3a1.5.2-2+b1_amd64.deb ...
Unpacking libjpeg62-turbo-dev:amd64 (1:1.5.2-2+b1) ...
Selecting previously unselected package libzip4:amd64.
Preparing to unpack .../7-libzip4_1.5.1-4_amd64.deb ...
Unpacking libzip4:amd64 (1.5.1-4) ...
Selecting previously unselected package libzip-dev:amd64.
Preparing to unpack .../8-libzip-dev_1.5.1-4_amd64.deb ...
Unpacking libzip-dev:amd64 (1.5.1-4) ...
Setting up libzip4:amd64 (1.5.1-4) ...
Setting up libjpeg62-turbo:amd64 (1:1.5.2-2+b1) ...
Setting up libjpeg62-turbo-dev:amd64 (1:1.5.2-2+b1) ...
Setting up libpng16-16:amd64 (1.6.36-6) ...
Setting up zlib1g-dev:amd64 (1:1.2.11.dfsg-1) ...
Setting up libzip-dev:amd64 (1.5.1-4) ...
Setting up libpng-dev:amd64 (1.6.36-6) ...
Setting up libfreetype6:amd64 (2.9.1-3) ...
Setting up libfreetype6-dev:amd64 (2.9.1-3) ...
Processing triggers for libc-bin (2.28-10) ...
Configuring for:
PHP Api Version:         20180731
Zend Module Api No:      20180731
Zend Extension Api No:   320180731
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for a sed that does not truncate output... /bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
checking for PHP prefix... /usr/local
checking for PHP includes... -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib
checking for PHP extension directory... /usr/local/lib/php/extensions/no-debug-non-zts-20180731
checking for PHP installed headers prefix... /usr/local/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... re2c
checking for re2c version... 1.1.1 (ok)
checking for gawk... no
checking for nawk... nawk
checking if nawk is broken... no
checking for GD support... yes, shared
checking for the location of libwebp... no
checking for the location of libjpeg... /usr/include/
checking for the location of libpng... no
checking for the location of libz... no
checking for the location of libXpm... no
checking for FreeType 2... /usr/include/
checking whether to enable JIS-mapped Japanese font support in GD... no
If configure fails try --with-webp-dir=<DIR>
checking for jpeg_read_header in -ljpeg... yes
checking for png_write_image in -lpng... yes
If configure fails try --with-xpm-dir=<DIR>
configure: error: freetype-config not found.
The command '/bin/sh -c apt-get update && apt-get install --no-install-recommends -y         libfreetype6-dev         libjpeg62-turbo-dev         libpng-dev         libzip-dev     && docker-php-ext-configure         gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/     && docker-php-ext-install         pdo_mysql         gd         opcache         zip     && apt-get remove -y         gcc         g++     && apt-get autoremove -y     && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 1
ERROR: Job failed: exit code 1
```

**Comment by vedmant** [comment] 2019-07-15 09:04
I have the same issue, why on earth the same tag now has new debian version?

**Comment by wglambert** [comment] 2019-07-15 19:40
Duplicate of https://github.com/docker-library/php/issues/865

The `stretch` variant is still updated so specifying `php-7.1-fpm-stretch` will go back to using an older version of `libfreetype6` that still contains `freetype-config`

**Closed by wglambert** 2019-07-15 19:40 UTC

**Comment by vedmant** [comment] 2019-07-15 19:53
@wglambert Yes, but it means I that lots containers that use php-7.1-fpm now just started to fail out of nothing. There is also an issue with mssql drivers, so php containers that use ms sql also fail to build.

**Comment by wglambert** [comment] 2019-07-15 20:57
Using explicit tags would help to prevent breakage from an update. The default OS variant for `php-7.1-fpm` changed from Debian Stretch to Debian Buster as Buster is now considered the stable release. 
Using `php-7.1-fpm-stretch` will resolve to the same OS base even while the default tag changes to a different one.

Specifying the OS variant is along the same lines as specifying version numbers.

For a full list of tags/shared-tags you can use https://github.com/docker-library/docs/blob/master/php/README.md#supported-tags-and-respective-dockerfile-links

**Comment by yosifkit** [comment] 2023-11-06 18:17
@jihadadulrazaqjasim, you'll need to install some dev dependencies for `gd` before configuring and installing it. There is an example on the Docker Hub page:

https://github.com/docker-library/docs/tree/84f820b83f5504ce0b0e8f8c8fae99f1c9f3f571/php#php-core-extensions
```dockerfile
FROM php:8.2-fpm
RUN apt-get update && apt-get install -y \
		libfreetype-dev \
		libjpeg62-turbo-dev \
		libpng-dev \
	&& docker-php-ext-configure gd --with-freetype --with-jpeg \
	&& docker-php-ext-install -j$(nproc) gd
```

**Comment by piotr-cz** [comment] 2024-10-04 12:59
@yosifkit 

This example doesn't work on alpine:

```
ERROR: unable to select packages:
  libfreetype-dev (no such package):
    required by: world[libfreetype-dev]
  libjpeg62-turbo-dev (no such package):
    required by: world[libjpeg62-turbo-dev]
```

**Comment by tianon** [comment] 2024-10-07 20:16
Package names on Alpine are different -- I believe `freetype-dev` and `libjpeg-turbo-dev` are the two packages you're looking for.

https://pkgs.alpinelinux.org/ is the best resource I'm aware of for finding the right package names for Alpine.

**Comment by piotr-cz** [comment] 2024-10-08 11:00
For Alpine & php 8.3, this works:

```Dockerfile
FROM php:8.3-fpm-alpine

RUN apk add --no-cache \
    freetype libjpeg-turbo libpng \
    freetype-dev libjpeg-turbo-dev libpng-dev \
    && docker-php-ext-configure gd --enable-gd --with-jpeg --with-freetype \
    && docker-php-ext-install -j$(nproc) gd \
    && apk del --no-cache freetype-dev libjpeg-turbo-dev libpng-dev
```

Source: https://github.com/mlocati/docker-php-extension-installer/blob/2.5.2/install-php-extensions#L831
