### ISSUE TITLE
PHP: Not mentioned all provided scripts for installing extensions

### ISSUE THREAD

**Issue by iBobik** [docker-library/docs#377] opened 2015-11-02 05:45 UTC
In section talking about installing PHP extensions there are mentioned `docker-php-ext-configure` and `docker-php-ext-install` but not `docker-php-ext-enable`.

Also there is not explained that if some extension is not in the distribution with PHP, it has to be installed by PECL and then enabled by `docker-php-ext-enable`.

I dont't understand much how it works adn don't know if I do it correctly. If somebody explains it in issue, I can prepare PR then.

**Comment by yosifkit** [comment] 2015-11-03 22:26
Yeah, that has been a TODO, perhaps @tianon can point you in the right direction.

As far as editing the markdown files, just change `php/content.md` and then `readme.md` will get updated by a bot.  You'll probably want to run `./markdownfmt.sh -d php/content.md` so that you can catch formatting issues before TravisCI in a PR.

**Comment by tianon** [comment] 2015-11-05 18:38
I think the `usage` is probably helpful here:
```console
root@c730d2986ef3:/# docker-php-ext-enable 
usage: /usr/local/bin/docker-php-ext-enable module-name [module-name ...]
   ie: /usr/local/bin/docker-php-ext-enable gd mysqli
       /usr/local/bin/docker-php-ext-enable pdo pdo_mysql

Possible values for module-name:
opcache.so
```

Once more modules get installed, they'll show up in the list of possible values (and specifying the `.so` suffix is optional), for example:
```Dockerfile
FROM php:5.6

RUN apt-get update && apt-get install -y libssl-dev && rm -rf /var/lib/apt/lists/*

RUN pecl install mongo \
    && docker-php-ext-enable mongo
```

And if I start a shell in the resulting image:
```console
dockroot@5d8b7c7a8f56:/# docker-php-ext-enable 
usage: /usr/local/bin/docker-php-ext-enable module-name [module-name ...]
   ie: /usr/local/bin/docker-php-ext-enable gd mysqli
       /usr/local/bin/docker-php-ext-enable pdo pdo_mysql

Possible values for module-name:
mongo.so opcache.so
root@5d8b7c7a8f56:/# cat /usr/local/etc/php/conf.d/docker-php-ext-mongo.ini 
extension=mongo.so
root@5d8b7c7a8f56:/# docker-php-ext-enable mongo

warning: mongo (mongo.so) is already loaded!

root@5d8b7c7a8f56:/# php -i | grep mongo
Additional .ini files parsed => /usr/local/etc/php/conf.d/docker-php-ext-mongo.ini
mongo
mongo.allow_empty_keys => 0 => 0
mongo.chunk_size => 261120 => 261120
mongo.cmd => $ => $
mongo.default_host => localhost => localhost
mongo.default_port => 27017 => 27017
mongo.is_master_interval => 15 => 15
mongo.long_as_object => 0 => 0
mongo.native_long => 1 => 1
mongo.ping_interval => 5 => 5
```

**Comment by iBobik** [comment] 2015-11-06 02:56
That is good explanation. Now let’s write it to README :-)



Jan Pobořil

2015-11-05 12:38 GMT-06:00 Tianon Gravi <notifications@github.com>:

**Comment by tianon** [comment] 2016-01-18 22:38
Doh, this is actually a duplicate of #323; sorry! :disappointed:

(and I'm going to go figure something out now to get this documented)

**Closed by tianon** 2016-01-18 22:38 UTC
