### ISSUE TITLE
Issue running rabbitmq with --platform=linux on Windows

### ISSUE THREAD

**Issue by mersadk** [docker-library/docs#1379] opened 2018-12-11 18:57 UTC
Docker for Windows experimentally supports [running Windows and Linux containers simultaneously](https://blogs.msdn.microsoft.com/premier_developer/2018/04/20/running-docker-windows-and-linux-containers-simultaneously/).
I'm running Windows 10 Pro as a host and Docker for Windows configured to run Windows containers.

When I try to run rabbitmq with following command
`docker run -d --platform=linux --hostname hba-rabbitmq --name hba-rabbitmq rabbitmq:3.7-alpine`

I get following error
```
2018-12-11 18:41:47.936 [info] <0.33.0> Application lager started on node 'rabbit@hba-rabbitmq'
2018-12-11 18:41:48.046 [error] <0.5.0> 
Error description:
    init:do_boot/3
    init:start_em/1
    rabbit:start_it/1 line 461
2018-12-11T18:41:48.286076700Z 
BOOT FAILED
===========
2018-12-11T18:41:48.286076700Z 
Error description:
    init:do_boot/3
    init:start_em/1
    rabbit:start_it/1 line 461
    rabbit:'-boot/0-fun-0-'/0 line 306
    rabbit_node_monitor:prepare_cluster_status_files/0 line 130
    rabbit_node_monitor:write_cluster_status/1 line 144
throw:{error,{could_not_write_file,"/var/lib/rabbitmq/mnesia/rabbit@hba-rabbitmq/cluster_nodes.config",
                                   eacces}}
Log file(s) (may contain more information):
   <stdout>
2018-12-11T18:41:48.286076700Z 
    rabbit:'-boot/0-fun-0-'/0 line 306
    rabbit_node_monitor:prepare_cluster_status_files/0 line 130
    rabbit_node_monitor:write_cluster_status/1 line 144
throw:{error,{could_not_write_file,"/var/lib/rabbitmq/mnesia/rabbit@hba-rabbitmq/cluster_nodes.config",
                                   eacces}}
Log file(s) (may contain more information):
   <stdout>
{"init terminating in do_boot",{error,{could_not_write_file,"/var/lib/rabbitmq/mnesia/rabbit@hba-rabbitmq/cluster_nodes.config",eacces}}}
init terminating in do_boot ({error,{could_not_write_file,/var/lib/rabbitmq/mnesia/rabbit@hba-rabbitmq/cluster_nodes.config,eacces}})
Crash dump is being written to: /var/log/rabbitmq/erl_crash.dump...done
```

When I switch to Linux containers and run same command (without `--platform=linux`) then it works.

**Comment by wglambert** [comment] 2018-12-11 20:16
Well I don't think there's anything we could change to the image to remedy LCOW issues. 

For filing issues to Microsoft about this the best I've found is on this [page](https://blogs.msdn.microsoft.com/premier_developer/2018/04/20/running-docker-windows-and-linux-containers-simultaneously/) at the bottom they say "Microsoft is currently tracking issues [here](https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/linux-containers)",  which at the bottom has a github repo for their documentation. So I'm not sure where you should file this.

**Comment by wglambert** [comment] 2018-12-11 20:19
There is this super-issue https://github.com/moby/moby/issues/33850 that is mentioned on the Microsoft post as "being used to track feature progress", but it looks like we've redirected people to this before to file their issue as with https://github.com/docker-library/rabbitmq/issues/257#issuecomment-387814657

**Comment by tianon** [comment] 2018-12-11 21:46
Yep, closing as a duplicate of https://github.com/docker-library/rabbitmq/issues/257. 👍

**Closed by tianon** 2018-12-11 21:46 UTC
Labels: question
