### ISSUE TITLE
Includes composer by default

### ISSUE THREAD

**Issue by yookoala** [docker-library/docs#1416] opened 2019-02-04 03:53 UTC
It'd be more handy if the php docker includes the composer CLI tool by default.

Composer is essential to modern PHP development. Although depending on zip and git, which would bloat up the image size a little, it does not depend on much library. Including composer would make the official image a lot more usable.

**Comment by tianon** [comment] 2019-02-04 15:09
Duplicate of https://github.com/docker-library/php/issues/344

**Closed by tianon** 2019-02-04 15:09 UTC
